# Changes here will be overwritten by Copier.
_commit: 1.4.4
_src_path: gh:mkdocstrings/handler-template
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2025'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC
insiders: false
language: Pydantic settings
project_description: A Pydantic Settings handler for mkdocstrings.
project_name: mkdocstrings-pydantic-settings
python_package_distribution_name: mkdocstrings-pydantic-settings
python_package_import_name: pydantic_settings
repository_name: mkdocstrings-pydantic-settings
repository_namespace: pawamoy
repository_provider: github.com

